apiVersion: v1
kind: Secret
metadata:
  name: <name_of_secret>
  annotations:
    avp.kubernetes.io/path: "<secret_path_on_vault>"
type: Opaque
stringData:
  <secret_key>: <key on vault but encode 64>
